test_user

CREATE TABLE test_user(
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(40) NOT NULL,
    PHONE VARCHAR(40),
    PRIMARY KEY ( ID )
    )ENGINE=InnoDB DEFAULT CHARSET=utf8;
