package org.omg.DynamicAny;


/**
* org/omg/DynamicAny/DynEnum.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /HUDSON3/workspace/8-2-build-macosx-x86_64/jdk8u101/7261/corba/src/share/classes/org/omg/DynamicAny/DynamicAny.idl
* Wednesday, June 22, 2016 2:43:37 AM PDT
*/


/**
    * DynEnum objects support the manipulation of IDL enumerated values.
    * The current position of a DynEnum is always -1.
    */
public interface DynEnum extends DynEnumOperations, org.omg.DynamicAny.DynAny, org.omg.CORBA.portable.IDLEntity 
{
} // interface DynEnum
